[package]
name = "rust_benchmark_worker"
version = "1.1.0"
edition = "2021"



[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
mimalloc = "0.1"
ndarray = "0.15"
serde_json = "1.0"
crossbeam = "0.8"