[package]
name = "rust_multitask"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
mimalloc = "0.1" 
ndarray = "0.15" 
